workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - counterino
      vars:
        PACKAGE_NAME: "io.codemagic.safwanapp"
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt