workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - counterino
      groups:
        - firebase_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.safwanapp"
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release --build-name=1.0.5 --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    triggering:
      events:                       # List the events that trigger builds
        - push
      branch_patterns:              # Include or exclude watched branches
        - pattern: 'main'
          include: true
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:104130086884:android:c294f62b1872cd386ae9f1
          groups:
            - androidTesters
          artifact_type: 'apk'